---
  - hosts: dev
    sudo: yes

    vars_files:
      - ./vars/dev.yml

    roles:
      - common
      - yarn
      - nodejs
      - ruby-common
      - rails
      - puma
      - nginx
      - letsencrypt
      - nginx
      - postgresql
      - monit
      - logrotate
      - collectd
      - delayed_job
